/** Deterministic zero-Effect Host runtime generator from canonical connector data. */
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { createHash } from 'node:crypto'

const root = new URL('../', import.meta.url)
const bridge = JSON.parse(await readFile(new URL('schema/bridge.json', root), 'utf8')) as {
  headers: Record<string, string>
  routes: { connector: Record<string, { method: string; path: string }> }
}
const auth = JSON.parse(await readFile(new URL('schema/connector-auth.json', root), 'utf8')) as unknown
const schemaSource = await readFile(new URL('schema/connector.ts', root), 'utf8')
const connectorRoutes = bridge.routes.connector
const contractHash = createHash('sha256')
  .update(JSON.stringify({ bridge, auth, schemaSource }))
  .digest('hex')
const generated = `/** @generated by scripts/generate-connector-runtime.ts — do not edit. */
import type { ChromeCommandId } from './ids.ts'
export const CONNECTOR_CONTRACT_SHA256 = '${contractHash}' as const
export const CONNECTOR_ROUTES = ${JSON.stringify({ handshake: connectorRoutes.connectorHandshake, poll: connectorRoutes.poll, result: connectorRoutes.result })} as const
export const CONNECTOR_HEADERS = ${JSON.stringify(bridge.headers)} as const
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue }
export type ConnectorHandshake = {\n  bridgeDisplayVersion: string\n  protocolFingerprint: string\n  bridgeEpoch: string\n  requestNonce: string\n  proof: string\n}
export type WireCommand = { id: ChromeCommandId; session: { key: string; groupTitle: string; foreground: boolean }; domain: 'tab' | 'page' | 'input' | 'system'; call: Record<string, JsonValue> }
export type WireFailure = { _tag: 'CommandRejected'; code: string; message: string; details?: JsonValue } | { _tag: 'CommandOutcomeUnknown'; message: string; cause: string }
export type WireResult = { id: ChromeCommandId; ok: true; value: JsonValue } | { id: ChromeCommandId; ok: false; error: WireFailure }
export type PollResponse = { type: 'command'; command: WireCommand; expectedExtensionId: string; expectedExtensionDisplayVersion: string; expectedProtocolFingerprint: string } | { type: 'none'; expectedExtensionId: string; expectedExtensionDisplayVersion: string; expectedProtocolFingerprint: string } | { type: 'incompatible'; expectedExtensionId: string; expectedExtensionDisplayVersion: string; actualExtensionDisplayVersion: string; expectedProtocolFingerprint: string; actualProtocolFingerprint: string }
const record=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v)
const text=(v:Record<string,unknown>,k:string):string=>{const x=v[k];if(typeof x!=='string'||x.length===0)throw new TypeError(k+' must be non-empty');return x}
const hex=(v:Record<string,unknown>,k:string):string=>{const x=text(v,k);if(!/^[a-f0-9]{64}$/.test(x))throw new TypeError(k+' must be hex256');return x}
const json=(v:unknown):JsonValue=>{if(v===null||typeof v==='string'||typeof v==='boolean'||(typeof v==='number'&&Number.isFinite(v)))return v as JsonValue;if(Array.isArray(v))return v.map(json);if(record(v))return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,json(x)]));throw new TypeError('not JSON')}
export const encodeJson=(v:unknown):string=>JSON.stringify(v)
export function decodeConnectorHandshake(value:unknown):ConnectorHandshake{if(!record(value))throw new TypeError('handshake object');return {bridgeDisplayVersion:text(value,'bridgeDisplayVersion'),protocolFingerprint:hex(value,'protocolFingerprint'),bridgeEpoch:hex(value,'bridgeEpoch'),requestNonce:hex(value,'requestNonce'),proof:hex(value,'proof')}}
export function decodeWireResult(value:unknown):WireResult{if(!record(value)||typeof value.ok!=='boolean')throw new TypeError('result object');const allowed=new Set(value.ok?['id','ok','value']:['id','ok','error']);if(Object.keys(value).some(k=>!allowed.has(k)))throw new TypeError('result unknown fields');const id=text(value,'id') as ChromeCommandId;if(value.ok)return{id,ok:true,value:json(value.value)};if(!record(value.error))throw new TypeError('result error');const tag=text(value.error,'_tag');if(tag==='CommandRejected')return{id,ok:false,error:{_tag:tag,code:text(value.error,'code'),message:text(value.error,'message'),...(value.error.details===undefined?{}:{details:json(value.error.details)})}};if(tag==='CommandOutcomeUnknown')return{id,ok:false,error:{_tag:tag,message:text(value.error,'message'),cause:text(value.error,'cause')}};throw new TypeError('result tag')}
`
const output = fileURLToPath(new URL('src/connector-runtime.generated.ts', root))
if (process.argv.includes('--check')) {
  if (await readFile(output, 'utf8') !== generated) throw new Error('generated connector runtime is stale')
} else await writeFile(output, generated)
