/** @generated by scripts/generate-connector-runtime.ts — do not edit. */
export const CONNECTOR_ROUTES = { handshake: { method: 'POST', path: '/connector/handshake' }, poll: { method: 'GET', path: '/next' }, result: { method: 'POST', path: '/result' } } as const
export const CONNECTOR_HEADERS = { id: 'x-dsh-chrome-connector-id', extensionId: 'x-dsh-chrome-extension-id', displayVersion: 'x-dsh-chrome-extension-display-version', protocolFingerprint: 'x-dsh-chrome-protocol-fingerprint', clientNonce: 'x-dsh-chrome-client-nonce', bridgeEpoch: 'x-dsh-chrome-bridge-epoch', requestNonce: 'x-dsh-chrome-request-nonce', bodySha256: 'x-dsh-chrome-body-sha256', proof: 'x-dsh-chrome-proof' } as const
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue }
export type ConnectorHandshake = {
  bridgeDisplayVersion: string
  protocolFingerprint: string
  bridgeEpoch: string
  requestNonce: string
  proof: string
}
export type WireCommand = { id: string; session: { key: string; groupTitle: string; foreground: boolean }; domain: 'tab' | 'page' | 'input' | 'system'; call: Record<string, JsonValue> }
export type WireFailure = { _tag: 'CommandRejected'; code: string; message: string; details?: JsonValue } | { _tag: 'CommandOutcomeUnknown'; message: string; cause: string }
export type WireResult = { id: string; ok: true; value: JsonValue } | { id: string; ok: false; error: WireFailure }
export type PollResponse = { type: 'command'; command: WireCommand; expectedExtensionId: string; expectedExtensionDisplayVersion: string; expectedProtocolFingerprint: string } | { type: 'none'; expectedExtensionId: string; expectedExtensionDisplayVersion: string; expectedProtocolFingerprint: string } | { type: 'incompatible'; expectedExtensionId: string; expectedExtensionDisplayVersion: string; actualExtensionDisplayVersion: string; expectedProtocolFingerprint: string; actualProtocolFingerprint: string }
const record=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v)
const text=(v:Record<string,unknown>,k:string):string=>{const x=v[k];if(typeof x!=='string'||x.length===0)throw new TypeError(`${k} must be non-empty`);return x}
const hex=(v:Record<string,unknown>,k:string):string=>{const x=text(v,k);if(!/^[a-f0-9]{64}$/.test(x))throw new TypeError(`${k} must be hex256`);return x}
const json=(v:unknown):JsonValue=>{if(v===null||typeof v==='string'||typeof v==='boolean'||(typeof v==='number'&&Number.isFinite(v)))return v as JsonValue;if(Array.isArray(v))return v.map(json);if(record(v))return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,json(x)]));throw new TypeError('not JSON')}
export const encodeJson=(v:unknown):string=>JSON.stringify(v)
export function decodeConnectorHandshake(value:unknown):ConnectorHandshake{if(!record(value))throw new TypeError('handshake object');return { bridgeDisplayVersion:text(value,'bridgeDisplayVersion'),protocolFingerprint:hex(value,'protocolFingerprint'),bridgeEpoch:hex(value,'bridgeEpoch'),requestNonce:hex(value,'requestNonce'),proof:hex(value,'proof') }}
export function decodeWireResult(value:unknown):WireResult{if(!record(value)||typeof value.ok!=='boolean')throw new TypeError('result object');const id=text(value,'id');if(value.ok)return{ id,ok:true,value:json(value.value) };if(!record(value.error))throw new TypeError('result error');const tag=text(value.error,'_tag');if(tag==='CommandRejected')return{ id,ok:false,error:{ _tag:tag,code:text(value.error,'code'),message:text(value.error,'message'),...(value.error.details===undefined?{}:{ details:json(value.error.details) }) } };if(tag==='CommandOutcomeUnknown')return{ id,ok:false,error:{ _tag:tag,message:text(value.error,'message'),cause:text(value.error,'cause') } };throw new TypeError('result tag')}
