/** @generated by scripts/generate-connector-runtime.ts — do not edit. */
import type { ChromeCommandId } from './ids.ts'
export const CONNECTOR_CONTRACT_SHA256 = 'ea7ac7652cc508008442d5cdcc84985785bdcd5887b3aaf9d9fc794c2dedc5da' as const
export const CONNECTOR_ROUTES = { 'handshake':{ 'method':'POST','path':'/connector/handshake','bodyLimit':'controlBody','responseLimit':'controlBody' },'poll':{ 'method':'GET','path':'/next','bodyLimit':'none','responseLimit':'requestBody' },'result':{ 'method':'POST','path':'/result','bodyLimit':'requestBody','responseLimit':'controlBody' } } as const
export const CONNECTOR_HEADERS = { 'ownerProtocolFingerprint':'x-dsh-chrome-protocol-fingerprint','ownerClientNonce':'x-dsh-chrome-owner-client-nonce','ownerBridgeEpoch':'x-dsh-chrome-owner-bridge-epoch','ownerRequestNonce':'x-dsh-chrome-owner-request-nonce','ownerBodySha256':'x-dsh-chrome-owner-body-sha256','ownerProof':'x-dsh-chrome-owner-proof' } as const
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue }
export type ConnectorHandshake = {
  bridgeDisplayVersion: string
  protocolFingerprint: string
  bridgeEpoch: string
  requestNonce: string
  proof: string
}
export type WireCommand = { id: ChromeCommandId; session: { key: string; groupTitle: string; foreground: boolean }; domain: 'tab' | 'page' | 'input' | 'system'; call: Record<string, JsonValue> }
export type WireFailure = { _tag: 'CommandRejected'; code: string; message: string; details?: JsonValue } | { _tag: 'CommandOutcomeUnknown'; message: string; cause: string }
export type WireResult = { id: ChromeCommandId; ok: true; value: JsonValue } | { id: ChromeCommandId; ok: false; error: WireFailure }
export type PollResponse = { type: 'command'; command: WireCommand; expectedExtensionId: string; expectedExtensionDisplayVersion: string; expectedProtocolFingerprint: string } | { type: 'none'; expectedExtensionId: string; expectedExtensionDisplayVersion: string; expectedProtocolFingerprint: string } | { type: 'incompatible'; expectedExtensionId: string; expectedExtensionDisplayVersion: string; actualExtensionDisplayVersion: string; expectedProtocolFingerprint: string; actualProtocolFingerprint: string }
const record=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v)
const text=(v:Record<string,unknown>,k:string):string=>{const x=v[k];if(typeof x!=='string'||x.length===0)throw new TypeError(k+' must be non-empty');return x}
const hex=(v:Record<string,unknown>,k:string):string=>{const x=text(v,k);if(!/^[a-f0-9]{64}$/.test(x))throw new TypeError(k+' must be hex256');return x}
const json=(v:unknown):JsonValue=>{if(v===null||typeof v==='string'||typeof v==='boolean'||(typeof v==='number'&&Number.isFinite(v)))return v as JsonValue;if(Array.isArray(v))return v.map(json);if(record(v))return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,json(x)]));throw new TypeError('not JSON')}
export const encodeJson=(v:unknown):string=>JSON.stringify(v)
export function decodeConnectorHandshake(value:unknown):ConnectorHandshake{if(!record(value))throw new TypeError('handshake object');return { bridgeDisplayVersion:text(value,'bridgeDisplayVersion'),protocolFingerprint:hex(value,'protocolFingerprint'),bridgeEpoch:hex(value,'bridgeEpoch'),requestNonce:hex(value,'requestNonce'),proof:hex(value,'proof') }}
export function decodeWireResult(value:unknown):WireResult{if(!record(value)||typeof value.ok!=='boolean')throw new TypeError('result object');const allowed=new Set(value.ok?['id','ok','value']:['id','ok','error']);if(Object.keys(value).some(k=>!allowed.has(k)))throw new TypeError('result unknown fields');const id=text(value,'id') as ChromeCommandId;if(value.ok)return{ id,ok:true,value:json(value.value) };if(!record(value.error))throw new TypeError('result error');const tag=text(value.error,'_tag');if(tag==='CommandRejected')return{ id,ok:false,error:{ _tag:tag,code:text(value.error,'code'),message:text(value.error,'message'),...(value.error.details===undefined?{}:{ details:json(value.error.details) }) } };if(tag==='CommandOutcomeUnknown')return{ id,ok:false,error:{ _tag:tag,message:text(value.error,'message'),cause:text(value.error,'cause') } };throw new TypeError('result tag')}
